// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProjectAssets(arg1) {
  return window['go']['main']['App']['AddProjectAssets'](arg1);
}

export function AddTranscriptLine(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddTranscriptLine'](arg1, arg2, arg3, arg4);
}

export function ApplyPlannedStream(arg1) {
  return window['go']['main']['App']['ApplyPlannedStream'](arg1);
}

export function ApplyStreamInfo() {
  return window['go']['main']['App']['ApplyStreamInfo']();
}

export function BeginTranscriptSession(arg1, arg2) {
  return window['go']['main']['App']['BeginTranscriptSession'](arg1, arg2);
}

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function CancelTranscribeDownload(arg1) {
  return window['go']['main']['App']['CancelTranscribeDownload'](arg1);
}

export function ConnectAnthropicAPIKey(arg1) {
  return window['go']['main']['App']['ConnectAnthropicAPIKey'](arg1);
}

export function ConnectAnthropicAccount() {
  return window['go']['main']['App']['ConnectAnthropicAccount']();
}

export function DefaultDownloadDir() {
  return window['go']['main']['App']['DefaultDownloadDir']();
}

export function DeleteContentSeries(arg1) {
  return window['go']['main']['App']['DeleteContentSeries'](arg1);
}

export function DeletePlannedStream(arg1) {
  return window['go']['main']['App']['DeletePlannedStream'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteProjectAsset(arg1, arg2) {
  return window['go']['main']['App']['DeleteProjectAsset'](arg1, arg2);
}

export function DeleteProjectDoc(arg1, arg2) {
  return window['go']['main']['App']['DeleteProjectDoc'](arg1, arg2);
}

export function DeleteRoutine(arg1) {
  return window['go']['main']['App']['DeleteRoutine'](arg1);
}

export function DeleteSeriesType(arg1) {
  return window['go']['main']['App']['DeleteSeriesType'](arg1);
}

export function DisconnectService(arg1) {
  return window['go']['main']['App']['DisconnectService'](arg1);
}

export function EditPlanDescription(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditPlanDescription'](arg1, arg2, arg3);
}

export function EndStreamSession() {
  return window['go']['main']['App']['EndStreamSession']();
}

export function GeneratePlanSuggestion(arg1, arg2, arg3) {
  return window['go']['main']['App']['GeneratePlanSuggestion'](arg1, arg2, arg3);
}

export function GenerateStreamOutline(arg1, arg2) {
  return window['go']['main']['App']['GenerateStreamOutline'](arg1, arg2);
}

export function GetActiveStreamSession() {
  return window['go']['main']['App']['GetActiveStreamSession']();
}

export function GetChannelSources() {
  return window['go']['main']['App']['GetChannelSources']();
}

export function GetChannelVideos(arg1) {
  return window['go']['main']['App']['GetChannelVideos'](arg1);
}

export function GetChatForStream(arg1, arg2) {
  return window['go']['main']['App']['GetChatForStream'](arg1, arg2);
}

export function GetChatHistory(arg1) {
  return window['go']['main']['App']['GetChatHistory'](arg1);
}

export function GetChatUserInfo(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetChatUserInfo'](arg1, arg2, arg3);
}

export function GetContentSeries() {
  return window['go']['main']['App']['GetContentSeries']();
}

export function GetDownloads() {
  return window['go']['main']['App']['GetDownloads']();
}

export function GetLiveStreamMeta(arg1) {
  return window['go']['main']['App']['GetLiveStreamMeta'](arg1);
}

export function GetLiveStreams() {
  return window['go']['main']['App']['GetLiveStreams']();
}

export function GetPastStreams(arg1) {
  return window['go']['main']['App']['GetPastStreams'](arg1);
}

export function GetPlannedStreams() {
  return window['go']['main']['App']['GetPlannedStreams']();
}

export function GetProfile() {
  return window['go']['main']['App']['GetProfile']();
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetRoutines() {
  return window['go']['main']['App']['GetRoutines']();
}

export function GetSeriesTypes() {
  return window['go']['main']['App']['GetSeriesTypes']();
}

export function GetServiceConfig() {
  return window['go']['main']['App']['GetServiceConfig']();
}

export function GetServiceStatuses() {
  return window['go']['main']['App']['GetServiceStatuses']();
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetStreamOutline(arg1) {
  return window['go']['main']['App']['GetStreamOutline'](arg1);
}

export function GetStreamdeckMultiActions() {
  return window['go']['main']['App']['GetStreamdeckMultiActions']();
}

export function GetStreams() {
  return window['go']['main']['App']['GetStreams']();
}

export function GetTranscribeJobs() {
  return window['go']['main']['App']['GetTranscribeJobs']();
}

export function GetTranscriptForStream(arg1) {
  return window['go']['main']['App']['GetTranscriptForStream'](arg1);
}

export function GetVideoDetails(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetVideoDetails'](arg1, arg2, arg3);
}

export function GetVideos(arg1) {
  return window['go']['main']['App']['GetVideos'](arg1);
}

export function GetYouTubeCategories() {
  return window['go']['main']['App']['GetYouTubeCategories']();
}

export function GetYouTubeLiveChat(arg1) {
  return window['go']['main']['App']['GetYouTubeLiveChat'](arg1);
}

export function GroupPastStreams(arg1) {
  return window['go']['main']['App']['GroupPastStreams'](arg1);
}

export function MarkAllChatRead() {
  return window['go']['main']['App']['MarkAllChatRead']();
}

export function NextEpisodeNumber(arg1) {
  return window['go']['main']['App']['NextEpisodeNumber'](arg1);
}

export function OutlineInProgress(arg1) {
  return window['go']['main']['App']['OutlineInProgress'](arg1);
}

export function PollTwitchDeviceAuth(arg1, arg2, arg3) {
  return window['go']['main']['App']['PollTwitchDeviceAuth'](arg1, arg2, arg3);
}

export function PollYouTubeDeviceAuth(arg1, arg2, arg3) {
  return window['go']['main']['App']['PollYouTubeDeviceAuth'](arg1, arg2, arg3);
}

export function PollYouTubeSubscribers() {
  return window['go']['main']['App']['PollYouTubeSubscribers']();
}

export function RefreshChannelInfo() {
  return window['go']['main']['App']['RefreshChannelInfo']();
}

export function SaveChannelSources(arg1) {
  return window['go']['main']['App']['SaveChannelSources'](arg1);
}

export function SaveChatMessages(arg1) {
  return window['go']['main']['App']['SaveChatMessages'](arg1);
}

export function SaveContentSeries(arg1) {
  return window['go']['main']['App']['SaveContentSeries'](arg1);
}

export function SavePlannedStream(arg1) {
  return window['go']['main']['App']['SavePlannedStream'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SaveProject(arg1) {
  return window['go']['main']['App']['SaveProject'](arg1);
}

export function SaveProjectDoc(arg1, arg2) {
  return window['go']['main']['App']['SaveProjectDoc'](arg1, arg2);
}

export function SaveRoutine(arg1) {
  return window['go']['main']['App']['SaveRoutine'](arg1);
}

export function SaveSeriesType(arg1) {
  return window['go']['main']['App']['SaveSeriesType'](arg1);
}

export function SaveServiceConfig(arg1) {
  return window['go']['main']['App']['SaveServiceConfig'](arg1);
}

export function SaveStreams(arg1) {
  return window['go']['main']['App']['SaveStreams'](arg1);
}

export function SearchTwitchCategories(arg1) {
  return window['go']['main']['App']['SearchTwitchCategories'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SendBroadcastChat(arg1) {
  return window['go']['main']['App']['SendBroadcastChat'](arg1);
}

export function SetDefaultContentSeries(arg1) {
  return window['go']['main']['App']['SetDefaultContentSeries'](arg1);
}

export function SetDefaultSeriesType(arg1) {
  return window['go']['main']['App']['SetDefaultSeriesType'](arg1);
}

export function SetPastStreamSeries(arg1, arg2) {
  return window['go']['main']['App']['SetPastStreamSeries'](arg1, arg2);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function SetStreamEpisode(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetStreamEpisode'](arg1, arg2, arg3);
}

export function StartDownload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2, arg3, arg4);
}

export function StartTranscription(arg1) {
  return window['go']['main']['App']['StartTranscription'](arg1);
}

export function StartTwitchDeviceAuth(arg1, arg2) {
  return window['go']['main']['App']['StartTwitchDeviceAuth'](arg1, arg2);
}

export function StartYouTubeDeviceAuth(arg1) {
  return window['go']['main']['App']['StartYouTubeDeviceAuth'](arg1);
}

export function StopTranscription() {
  return window['go']['main']['App']['StopTranscription']();
}

export function SubscribeTwitchEvents(arg1) {
  return window['go']['main']['App']['SubscribeTwitchEvents'](arg1);
}

export function TranscribeDownload(arg1) {
  return window['go']['main']['App']['TranscribeDownload'](arg1);
}

export function UngroupPastStreams(arg1) {
  return window['go']['main']['App']['UngroupPastStreams'](arg1);
}

export function UpdateProjectAsset(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProjectAsset'](arg1, arg2, arg3);
}

export function UsedEpisodeNumbers(arg1) {
  return window['go']['main']['App']['UsedEpisodeNumbers'](arg1);
}
