// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTranscriptLine(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddTranscriptLine'](arg1, arg2, arg3, arg4);
}

export function BeginTranscriptSession(arg1, arg2) {
  return window['go']['main']['App']['BeginTranscriptSession'](arg1, arg2);
}

export function DisconnectService(arg1) {
  return window['go']['main']['App']['DisconnectService'](arg1);
}

export function GetChannelSources() {
  return window['go']['main']['App']['GetChannelSources']();
}

export function GetChatHistory(arg1) {
  return window['go']['main']['App']['GetChatHistory'](arg1);
}

export function GetChatUserInfo(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetChatUserInfo'](arg1, arg2, arg3);
}

export function GetLiveStreams() {
  return window['go']['main']['App']['GetLiveStreams']();
}

export function GetPastStreams(arg1) {
  return window['go']['main']['App']['GetPastStreams'](arg1);
}

export function GetProfile() {
  return window['go']['main']['App']['GetProfile']();
}

export function GetServiceConfig() {
  return window['go']['main']['App']['GetServiceConfig']();
}

export function GetServiceStatuses() {
  return window['go']['main']['App']['GetServiceStatuses']();
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetStreams() {
  return window['go']['main']['App']['GetStreams']();
}

export function GetTranscriptForStream(arg1) {
  return window['go']['main']['App']['GetTranscriptForStream'](arg1);
}

export function GetVideoDetails(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetVideoDetails'](arg1, arg2, arg3);
}

export function GetVideos(arg1) {
  return window['go']['main']['App']['GetVideos'](arg1);
}

export function GetYouTubeLiveChat(arg1) {
  return window['go']['main']['App']['GetYouTubeLiveChat'](arg1);
}

export function GroupPastStreams(arg1) {
  return window['go']['main']['App']['GroupPastStreams'](arg1);
}

export function MarkAllChatRead() {
  return window['go']['main']['App']['MarkAllChatRead']();
}

export function PollTwitchDeviceAuth(arg1, arg2, arg3) {
  return window['go']['main']['App']['PollTwitchDeviceAuth'](arg1, arg2, arg3);
}

export function PollYouTubeDeviceAuth(arg1, arg2, arg3) {
  return window['go']['main']['App']['PollYouTubeDeviceAuth'](arg1, arg2, arg3);
}

export function SaveChannelSources(arg1) {
  return window['go']['main']['App']['SaveChannelSources'](arg1);
}

export function SaveChatMessages(arg1) {
  return window['go']['main']['App']['SaveChatMessages'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SaveServiceConfig(arg1) {
  return window['go']['main']['App']['SaveServiceConfig'](arg1);
}

export function SaveStreams(arg1) {
  return window['go']['main']['App']['SaveStreams'](arg1);
}

export function SendBroadcastChat(arg1) {
  return window['go']['main']['App']['SendBroadcastChat'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function StartTranscription(arg1) {
  return window['go']['main']['App']['StartTranscription'](arg1);
}

export function StartTwitchDeviceAuth(arg1, arg2) {
  return window['go']['main']['App']['StartTwitchDeviceAuth'](arg1, arg2);
}

export function StartYouTubeDeviceAuth(arg1) {
  return window['go']['main']['App']['StartYouTubeDeviceAuth'](arg1);
}

export function StopTranscription() {
  return window['go']['main']['App']['StopTranscription']();
}

export function SubscribeTwitchEvents(arg1) {
  return window['go']['main']['App']['SubscribeTwitchEvents'](arg1);
}

export function UngroupPastStreams(arg1) {
  return window['go']['main']['App']['UngroupPastStreams'](arg1);
}
