// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisconnectService(arg1) {
  return window['go']['main']['App']['DisconnectService'](arg1);
}

export function GetChannelSources() {
  return window['go']['main']['App']['GetChannelSources']();
}

export function GetServiceStatuses() {
  return window['go']['main']['App']['GetServiceStatuses']();
}

export function GetStreams() {
  return window['go']['main']['App']['GetStreams']();
}

export function PollTwitchDeviceAuth(arg1, arg2, arg3) {
  return window['go']['main']['App']['PollTwitchDeviceAuth'](arg1, arg2, arg3);
}

export function PollYouTubeDeviceAuth(arg1, arg2, arg3) {
  return window['go']['main']['App']['PollYouTubeDeviceAuth'](arg1, arg2, arg3);
}

export function StartTwitchDeviceAuth(arg1, arg2) {
  return window['go']['main']['App']['StartTwitchDeviceAuth'](arg1, arg2);
}

export function StartYouTubeDeviceAuth(arg1) {
  return window['go']['main']['App']['StartYouTubeDeviceAuth'](arg1);
}
