// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddBrandAssets():Promise<Array<main.BrandAsset>>;

export function AddProjectAssets(arg1:string):Promise<main.Project>;

export function AddTranscriptLine(arg1:number,arg2:number,arg3:number,arg4:string):Promise<void>;

export function ApplyPlannedStream(arg1:string):Promise<Array<string>>;

export function ApplyStreamInfo():Promise<Array<string>>;

export function ApplyStreamInfoForPlan(arg1:string):Promise<Array<string>>;

export function BeginTranscriptSession(arg1:string,arg2:string):Promise<number>;

export function CancelDownload():Promise<void>;

export function CancelEditRun():Promise<void>;

export function CancelKickAuth():Promise<void>;

export function CancelTikTokAuth():Promise<void>;

export function CancelXAuth():Promise<void>;

export function CancelTranscribeDownload(arg1:string):Promise<void>;

export function ConcludePlannedStream(arg1:string):Promise<void>;

export function ConnectAnthropicAPIKey(arg1:string):Promise<main.ServiceStatus>;

export function ConnectAnthropicAccount():Promise<main.ServiceStatus>;

export function ConnectInstagram():Promise<main.ServiceStatus>;

export function ConnectOpenAIAPIKey(arg1:string):Promise<main.ServiceStatus>;

export function ConnectOpenAIAccount():Promise<main.ServiceStatus>;

export function DefaultDownloadDir():Promise<string>;

export function DefaultEditWorkspaceDir():Promise<string>;

export function DeleteBrandAsset(arg1:string):Promise<Array<main.BrandAsset>>;

export function DeleteBrandLink(arg1:string):Promise<Array<main.BrandLink>>;

export function DeleteContentSeries(arg1:string):Promise<void>;

export function DeleteLocalStream(arg1:string):Promise<void>;

export function DeletePlannedStream(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteProjectAsset(arg1:string,arg2:string):Promise<main.Project>;

export function DeleteProjectDoc(arg1:string,arg2:string):Promise<main.Project>;

export function DeleteRoutine(arg1:string):Promise<void>;

export function DeleteSeriesType(arg1:string):Promise<void>;

export function DeleteVideoPlan(arg1:string):Promise<void>;

export function DisconnectService(arg1:string):Promise<void>;

export function EditPlanDescription(arg1:string,arg2:string,arg3:string):Promise<string>;

export function EndStreamSession():Promise<void>;

export function GenerateDownloadThumbnail(arg1:string):Promise<string>;

export function GenerateEditDirections(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GeneratePlanSuggestion(arg1:string,arg2:string,arg3:number):Promise<main.PlanSuggestion>;

export function GeneratePlanThumbnail(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.PlanThumbnail>;

export function GenerateStreamOutline(arg1:string,arg2:number):Promise<main.StreamOutline>;

export function GetActiveStreamSession():Promise<main.ActiveStreamSession>;

export function GetBrandAssets():Promise<Array<main.BrandAsset>>;

export function GetBrandLinks():Promise<Array<main.BrandLink>>;

export function GetFacebookLiveChat():Promise<main.LiveChatPage>;

export function GetInstagramLiveChat():Promise<main.LiveChatPage>;

export function GetKickChatIDs():Promise<main.KickChatIDs>;

export function GetChannelSources():Promise<Array<main.ChannelSource>>;

export function GetChannelVideos(arg1:string):Promise<Array<main.Video>>;

export function GetChatForStream(arg1:string,arg2:number):Promise<Array<main.StoredChatMessage>>;

export function GetChatHistory(arg1:number):Promise<Array<main.StoredChatMessage>>;

export function GetChatUserInfo(arg1:string,arg2:string,arg3:string):Promise<main.ChatUserInfo>;

export function GetContentSeries():Promise<Array<main.ContentSeries>>;

export function GetDownloads():Promise<Array<main.DownloadedVideo>>;

export function GetEditWorkspace(arg1:string):Promise<main.EditWorkspaceInfo>;

export function GetEditorTools():Promise<main.EditorTools>;

export function GetLiveEventHistory(arg1:number):Promise<Array<main.StoredLiveEvent>>;

export function GetLiveEventsBefore(arg1:number,arg2:number):Promise<Array<main.StoredLiveEvent>>;

export function GetLiveEventsForStream(arg1:string,arg2:number):Promise<Array<main.StoredLiveEvent>>;

export function GetLiveStreamMeta(arg1:string):Promise<main.LiveStreamMeta>;

export function GetLiveStreams():Promise<Array<main.LiveStream>>;

export function GetMCPStatus():Promise<main.MCPStatus>;

export function GetPastStreams(arg1:boolean):Promise<Array<main.PastStream>>;

export function GetPlanInfoStatus(arg1:string):Promise<Array<main.PlanChannelInfo>>;

export function GetPlanSessions():Promise<Array<main.PlanSessionInfo>>;

export function GetPlannedStreams():Promise<Array<main.PlannedStream>>;

export function GetProfile():Promise<main.Profile>;

export function GetProjects():Promise<Array<main.Project>>;

export function GetRoutines():Promise<Array<main.Routine>>;

export function GetSeriesTypes():Promise<Array<main.SeriesType>>;

export function GetServiceConfig():Promise<main.ServiceConfig>;

export function GetServiceStatuses():Promise<Array<main.ServiceStatus>>;

export function GetSetting(arg1:string):Promise<string>;

export function GetStreamOutline(arg1:string):Promise<main.StreamOutline>;

export function GetStreamdeckMultiActions():Promise<Array<main.StreamdeckMultiAction>>;

export function GetStreams():Promise<Array<main.Stream>>;

export function GetTranscribeJobs():Promise<Array<main.TranscribeJob>>;

export function GetTranscriptForStream(arg1:string):Promise<Array<main.TranscriptLineRec>>;

export function GetVideoDetails(arg1:string,arg2:string,arg3:boolean):Promise<main.VideoDetails>;

export function GetVideoPlans():Promise<Array<main.VideoPlan>>;

export function GetVideos(arg1:boolean):Promise<main.VideoList>;

export function GetYouTubeCategories():Promise<Array<main.ServiceCategory>>;

export function GetYouTubeLiveChat(arg1:string):Promise<main.LiveChatPage>;

export function GroupPastStreams(arg1:Array<string>):Promise<void>;

export function KickRedirectURI():Promise<string>;

export function TikTokRedirectURI():Promise<string>;

export function XRedirectURI():Promise<string>;

export function ListAppSkills():Promise<Array<main.AppSkill>>;

export function ListFacebookPages():Promise<Array<main.FBPageInfo>>;

export function MarkAllChatRead():Promise<void>;

export function MarkAllLiveEventsRead():Promise<void>;

export function MoveDownloadFolder(arg1:string):Promise<number>;

export function MoveEditWorkspaceFolder(arg1:string):Promise<number>;

export function NextEpisodeNumber(arg1:string):Promise<number>;

export function OutlineInProgress(arg1:string):Promise<boolean>;

export function PollFacebookDeviceAuth(arg1:string,arg2:string,arg3:string):Promise<main.AuthPollResult>;

export function PollKickAuth():Promise<main.AuthPollResult>;

export function PollTikTokAuth():Promise<main.AuthPollResult>;

export function PollXAuth():Promise<main.AuthPollResult>;

export function PollTwitchDeviceAuth(arg1:string,arg2:string,arg3:string):Promise<main.AuthPollResult>;

export function PollYouTubeDeviceAuth(arg1:string,arg2:string,arg3:string):Promise<main.AuthPollResult>;

export function PressHotkey(arg1:number,arg2:boolean,arg3:boolean,arg4:boolean,arg5:boolean):Promise<void>;

export function RecycleMCPToken():Promise<main.MCPStatus>;

export function RefreshChannelInfo():Promise<void>;

export function ResetAppSkill(arg1:string):Promise<main.AppSkill>;

export function ResetPlannedStream(arg1:string):Promise<void>;

export function UploadPlanThumbnail():Promise<main.PlanThumbnail>;

export function SaveAppSkill(arg1:string,arg2:string):Promise<main.AppSkill>;

export function SaveBrandLink(arg1:main.BrandLink):Promise<Array<main.BrandLink>>;

export function SaveChannelSources(arg1:Array<main.ChannelSource>):Promise<void>;

export function SaveChatMessages(arg1:Array<main.StoredChatMessage>):Promise<void>;

export function SaveContentSeries(arg1:main.ContentSeries):Promise<main.ContentSeries>;

export function SaveLiveEvents(arg1:Array<main.StoredLiveEvent>):Promise<void>;

export function SavePlannedStream(arg1:main.PlannedStream):Promise<main.PlannedStream>;

export function SaveProfile(arg1:main.Profile):Promise<void>;

export function SaveProject(arg1:main.Project):Promise<main.Project>;

export function SaveProjectDoc(arg1:string,arg2:main.ProjectDoc):Promise<main.Project>;

export function SaveRoutine(arg1:main.Routine):Promise<main.Routine>;

export function SaveSeriesType(arg1:main.SeriesType):Promise<main.SeriesType>;

export function SaveServiceConfig(arg1:main.ServiceConfig):Promise<void>;

export function SaveStreams(arg1:Array<main.Stream>):Promise<void>;

export function InstallEditorTools():Promise<main.EditorTools>;

export function PrepareEditWorkspace(arg1:string):Promise<main.EditWorkspaceInfo>;

export function SaveVideoPlan(arg1:main.VideoPlan):Promise<main.VideoPlan>;

export function SearchKickCategories(arg1:string):Promise<Array<main.ServiceCategory>>;

export function SearchTwitchCategories(arg1:string):Promise<Array<main.ServiceCategory>>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFacebookPage(arg1:string):Promise<main.ServiceStatus>;

export function SendBroadcastChat(arg1:string):Promise<Array<main.BroadcastSendResult>>;

export function SetDefaultContentSeries(arg1:string):Promise<void>;

export function SetDefaultSeriesType(arg1:string):Promise<void>;

export function SetHideFromCapture(arg1:boolean):Promise<void>;

export function SetPastStreamSeries(arg1:Array<string>,arg2:string):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function SetStreamEpisode(arg1:Array<string>,arg2:number,arg3:string):Promise<void>;

export function SetupClaudeMCP():Promise<main.MCPStatus>;

export function StartDownload(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:Array<string>):Promise<void>;

export function StartEditRun(arg1:string,arg2:string):Promise<void>;

export function StartTranscription(arg1:string):Promise<void>;

export function StartFacebookDeviceAuth(arg1:string,arg2:string):Promise<main.DeviceCodeInfo>;

export function StartKickAuth(arg1:string,arg2:string):Promise<string>;

export function StartTikTokAuth(arg1:string,arg2:string):Promise<string>;

export function StartXAuth(arg1:string,arg2:string):Promise<string>;

export function StartTwitchDeviceAuth(arg1:string,arg2:string):Promise<main.DeviceCodeInfo>;

export function StartYouTubeDeviceAuth(arg1:string):Promise<main.DeviceCodeInfo>;

export function StopTranscription():Promise<void>;

export function SubscribeTwitchEvents(arg1:string):Promise<Array<string>>;

export function SyncPlatformEvents():Promise<Array<main.StoredLiveEvent>>;

export function TranscribeDownload(arg1:string):Promise<void>;

export function UngroupPastStreams(arg1:string):Promise<void>;

export function UpdateBrandAsset(arg1:string,arg2:string):Promise<Array<main.BrandAsset>>;

export function UpdateProjectAsset(arg1:string,arg2:string,arg3:string):Promise<main.Project>;

export function UsedEpisodeNumbers(arg1:string):Promise<Array<number>>;
